# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Cantiga\CoreBundle\Entity\User:
            algorithm: sha256
            encode_as_base64: true
            iterations: 0
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        default_cantiga_provider:
            id: cantiga.user_provider
            
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|error)/
            security: false
        public_area:
            pattern:   ^/(api|pub)/
            anonymous: ~
        login_area:
            pattern:   ^/auth/login$
            anonymous: ~
        cantiga_area:
            pattern:  ^(/$|/user/|/admin/|/project/|/s/|/group/|/area/|/auth/check|/auth/logout)
            provider: default_cantiga_provider
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path:    cantiga_auth_login
                check_path:    cantiga_auth_check
                default_target_path: cantiga_home_page
            logout:
                path:   cantiga_auth_logout
                target: cantiga_home_page
            remember_me:
                secret:  "%secret%"
                lifetime: 604800
                path:     /

    access_control:
        - { path: ^/auth/(login|check)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pub|api)/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(user|project|group|area|s), roles: ROLE_USER }
        - { path: ^/(user|project|group|area|s)/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/$, roles: ROLE_USER }
