Cantiga\KnowledgeBundle\Entity\FaqQuestion:
    repositoryClass:                    Cantiga\KnowledgeBundle\Repository\FaqQuestionRepository
    table:                              cantiga_faq_question
    type:                               entity

    indexes:
        Q_INDEX_1:
            columns:
                -                       level

    fields:
        id:
            generator:
                strategy:               AUTO
            id:                         true
            type:                       integer
        topic:
            type:                       string
        answer:
            type:                       text
        level:
            type:                       integer

    manyToOne:
        category:
            cascade:
                -                       persist
            inversedBy:                 questions
            targetEntity:               Cantiga\KnowledgeBundle\Entity\FaqCategory
