Cantiga\KnowledgeBundle\Entity\MaterialsCategory:
    repositoryClass:                    Cantiga\KnowledgeBundle\Repository\MaterialsCategoryRepository
    table:                              cantiga_materials_category
    type:                               entity

    fields:
        id:
            generator:
                strategy:               AUTO
            id:                         true
            type:                       integer
        name:
            type:                       string

    oneToMany:
        files:
            cascade:
                -                       persist
                -                       remove
            mappedBy:                   category
            targetEntity:               Cantiga\KnowledgeBundle\Entity\MaterialsFile

    lifecycleCallbacks:
        postLoad:
            -                           initializeCollections
