_discussion_controller:                                                                                                                                                   
    resource: "@CantigaDiscussionBundle/Controller/DiscussionController.php"                                                                                                      
    type:     annotation
_management_controller:                                                                                                                                                   
    resource: "@CantigaDiscussionBundle/Controller/ManagementController.php"                                                                                                      
    type:     annotation
